// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RatingRuleModel) DeepCopyInto(out *RatingRuleModel) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RatingRuleModel.
func (in *RatingRuleModel) DeepCopy() *RatingRuleModel {
	if in == nil {
		return nil
	}
	out := new(RatingRuleModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RatingRuleModel) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RatingRuleModelList) DeepCopyInto(out *RatingRuleModelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RatingRuleModel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RatingRuleModelList.
func (in *RatingRuleModelList) DeepCopy() *RatingRuleModelList {
	if in == nil {
		return nil
	}
	out := new(RatingRuleModelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RatingRuleModelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RatingRuleModelSpec) DeepCopyInto(out *RatingRuleModelSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RatingRuleModelSpec.
func (in *RatingRuleModelSpec) DeepCopy() *RatingRuleModelSpec {
	if in == nil {
		return nil
	}
	out := new(RatingRuleModelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RatingRuleModelStatus) DeepCopyInto(out *RatingRuleModelStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RatingRuleModelStatus.
func (in *RatingRuleModelStatus) DeepCopy() *RatingRuleModelStatus {
	if in == nil {
		return nil
	}
	out := new(RatingRuleModelStatus)
	in.DeepCopyInto(out)
	return out
}
