kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rating-operator-engine
subjects:
- kind: ServiceAccount
  name: rating-operator-engine
roleRef:
  kind: Role
  name: rating-operator-engine
  apiGroup: rbac.authorization.k8s.io
