apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ratingruleinstances.rating.alterway.fr
spec:
  group: rating.alterway.fr
  names:
    kind: RatingRuleInstance
    listKind: RatingRuleInstanceList
    plural: ratingruleinstances
    singular: ratingruleinstance
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: RatingRuleInstance is the Schema for the RatingRuleInstances API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: RatingRuleInstanceSpec defines the desired state of RatingRuleInstance
          properties:
            metric:
              type: string
            name:
              type: string
            timeframe:
              type: string
            cpu:
              type: string
            memory:
              type: string
            price:
              type: string
          required:
          - metric
          - name
          - timeframe
          type: object
        status:
          description: RatingRuleInstanceStatus defines the observed state of RatingRuleInstance
          properties:
            metric:
              type: string
            name:
              type: string
            timeframe:
              type: string
            cpu:
              type: string
            memory:
              type: string
            price:
              type: string
          required:
          - metric
          - name
          - timeframe
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
